name: Arduino ESP8266 Build

on: 
  push:
    branches:
      - master

concurrency:
  group: "Arduino ESP8266 Build"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI (Prebuilt)
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Compile Sketches
        uses: porrey/EEPROM-Storage/.github/workflows/arduino-build.yml@master
        with:
          board: "esp8266:esp8266:espino"
