name: Arduino Build 2

on: 
  push:
    branches:
      - master

concurrency:
  group: "Arduino-Build 2"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI (Prebuilt)
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install renesas  # Install board

      - name: Compile Cache Sketches
        run: |
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/address/address.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/advanced-structure/advanced-structure.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/assignment/assignment.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/basic-structure/basic-structure.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/byte-index/byte-index.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/demo/demo.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/scope/scope.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/shadow/shadow.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Cache/simple/simple.ino || exit 1
      
      - name: Compile General Sketches
        run: |
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/General/address/address.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/General/clear/clear.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/General/debug/debug.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/General/sizeof/sizeof.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/General/tests/tests.ino || exit 1
          
      - name: Compile Storage Sketches
        run: |          
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/address/address.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/advanced-structure/advanced-structure.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/assignment/assignment.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/basic-structure/basic-structure.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/byte-index/byte-index.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/checksum/checksum.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/copy-to/copy-to.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/demo/demo.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/invalid-address/invalid-address.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/scope/scope.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/shadow/shadow.ino || exit 1
          arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi --library src --library $HOME/Arduino/libraries/ examples/Storage/simple/simple.ino || exit 1
  
