name: Arduino Mega 2560 Build

on: 
  push:
    branches:
      - master

concurrency:
  group: "Arduino Mega 2560 Build"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI (Prebuilt)
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Sketches
        uses: .github/actions/arduino-build
        with:
          board: "arduino:avr:mega"
