name: Particle Compile

on:
  push:
    branches:
      - v2.0.0
  pull_request:
    branches:
      - v2.0.0

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Particle CLI
        run: |
          npm install -g particle-cli
          particle --version

      - name: Authenticate Particle CLI
        run: |
          particle login --token ${{ secrets.PARTICLE_ACCESS_TOKEN }}
        
      - name: Compile firmware
        run: |
          particle compile photon examples/General/tests --saveTo firmware.bin
